name: calculator_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  camera: ^0.11.0
  cloud_firestore: ^4.17.4
  firebase_core: ^2.31.1
  firebase_database: ^10.5.6
  flutter:
    sdk: flutter
  http: ^1.2.1
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
